export HADOOP_HOME=/usr/local/hadoop
export HDFS_NAMENODE_USER="root"
export HDFS_DATANODE_USER="root"
export HDFS_SECONDARYNAMENODE_USER="root"
export YARN_RESOURCEMANAGER_USER="root"
export YARN_NODEMANAGER_USER="root"
export PIG_HOME = /content/pig-0.16.0
export PATH  = $PATH:/content/pig-0.16.0/bin
export PIG_CLASSPATH = /usr/local/hadoop/etc/hadoop
